server:
  port: 8090
docker:
  host: npipe:////./pipe/docker_engine
  image: eclipse-temurin:17-jdk
  first-init: false
  container:
    cpu-count: 1
    memory: 100000000
    memory-swap: 0
    network-disabled: true
    read-only-rootfs: false
logging:
  level:
    cc.geektip.geekojcodesandbox: DEBUG