# 生产环境配置文件
server:
  port: 8090
geekoj:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  nacos:
    host: ${NACOS_HOST:localhost}
    port: ${NACOS_PORT:8848}
    username: ${NACOS_USERNAME:nacos}
    password: ${NACOS_PASSWORD:nacos}
  code-sandbox:
    x-service-key: ${CODE_SANDBOX_X_SERVICE_KEY:162d6319-eca7-10c6-8005-14f7c3d296aa}
    judge-mode: ${CODE_SANDBOX_JUDGE_MODE:acm}
    docker:
      host: ${DOCKER_HOST:unix:///var/run/docker.sock}
      first-init: ${DOCKER_FIRST_INIT:true}
      container:
        cpu-count: ${DOCKER_CONTAINER_CPU_COUNT:1}
        memory: ${DOCKER_CONTAINER_MEMORY:256}
logging:
  level:
    cc.geektip.geekojcodesandbox: DEBUG