spring:
  application:
    name: geekoj-code-sandbox
  profiles:
    active: ${geekoj.profiles.active}
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      discovery:
        heart-beat:
          enabled: true
        enabled: true
        server-addr: ${geekoj.nacos.host}:${geekoj.nacos.port}
        username: ${geekoj.nacos.username}
        password: ${geekoj.nacos.password}
code-sandbox:
  judge-mode: ${geekoj.code-sandbox.judge-mode}
  x-service-key: ${geekoj.code-sandbox.x-service-key}
  code-cache-path: ${geekoj.code-sandbox.code-cache-path}
  host-code-cache-path: ${geekoj.code-sandbox.host-code-cache-path}
  language-settings:
    java:
      image: ibm-semeru-runtimes:open-21-jdk-jammy
      main-file: Main.java
      compile-time-out: 10010
      run-time-out: 10010
      compile-command: javac -encoding utf-8 /app/Main.java
      run-command: java -cp /app Main
    cpp:
      image: gcc:11
      main-file: Main.cpp
      compile-time-out: 10010
      run-time-out: 10010
      compile-command: g++ -O2 -fsanitize=address -o /app/Main /app/Main.cpp
      run-command: /app/Main
    go:
      image: golang:1.21
      main-file: main.go
      compile-time-out: 10010
      run-time-out: 10010
      compile-command: go build -o /app/main /app/main.go
      run-command: /app/main

docker:
  host: ${geekoj.code-sandbox.docker.host}
  first-init: ${geekoj.code-sandbox.docker.first-init}
  container:
    cpu-count: ${geekoj.code-sandbox.docker.container.cpu-count}
    memory: ${geekoj.code-sandbox.docker.container.memory} # MB
    memory-swap: 0
    network-disabled: true
    read-only-rootfs: false