server:
  port: 8090

code-sandbox:
  global-code-path: tmpCode
  language-settings:
    java:
      main-file: Main.java
      compile-time-out: 30000
      run-time-out: 5000
      compile-command: javac -encoding utf-8 /app/Main.java
      run-command: java -cp /app Main
    cpp:
      main-file: Main.cpp
      compile-time-out: 30000
      run-time-out: 5000
      compile-command: g++ -o /app/Main /app/Main.cpp
      run-command: /app/Main
    golang:
      main-file: main.go
      compile-time-out: 30000
      run-time-out: 5000
      compile-command: go build -o /app/main /app/main.go
      run-command: /app/main

docker:
  host: npipe:////./pipe/docker_engine
  image: eclipse-temurin:17-jdk
  first-init: false
  container:
    cpu-count: 1
    memory: 100000000
    memory-swap: 0
    network-disabled: true
    read-only-rootfs: true

logging:
  level:
    cc.geektip.geekojcodesandbox: DEBUG